name: Build MicroPython

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MicroPython
        uses: actions/checkout@v3
        with:
          repository: micropython/micropython
          path: micropython

      - name: Checkout MicroPython MCUDev DevEBox STM32H743
        uses: actions/checkout@v3
        with:
          path: MicroPython-MCUDev-DevEBox-STM32H743

      - name: Copy MCUDEV_DEVEBOX_H743 to micropython/ports/stm32/boards
        run: |
          rm -rf micropython/ports/stm32/boards/MCUDEV_DEVEBOX_H743
          cp -r MicroPython-MCUDev-DevEBox-STM32H743/MCUDEV_DEVEBOX_H743 micropython/ports/stm32/boards

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libffi-dev pkg-config
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          sudo apt install -y python3

      - name: Build
        run: |
          cd micropython/ports/stm32
          make submodules
          make BOARD=MCUDEV_DEVEBOX_H743

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: micropython/ports/stm32/build-MCUDEV_DEVEBOX_H743/firmware*
